services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  backend:
    build: ./backend
    ports:
      - "8080:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/driver_monitoring
      - PORT=5000
      - JWT_SECRET=supersecretkey123
    depends_on:
      - mongodb
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8080
    restart: always

  yolo:
    build: ./yolo
    ports:
      - "5001:5001"
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/video1:/dev/video1"
      - "/dev/video2:/dev/video2"
      - "/dev/video10:/dev/video10"
      - "/dev/video11:/dev/video11"
      - "/dev/dma_heap:/dev/dma_heap"
      - "/dev/vchiq:/dev/vchiq"
    privileged: true
    ipc: host
    environment:
      - API_URL=http://backend:5000/api/events
      - SHOW_VIDEO=False
      - FLASK_PORT=5001
      - DRIVER_ID=206570
      - IP_CAMERA_URL=tcp://host.docker.internal:4748
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
